language: node_js
node_js:
- '0.10'
- '0.12'
sudo: false
deploy:
  provider: npm
  email: jakob.mattsson@gmail.com
  skip_cleanup: true
  api_key:
    secure: g6u4nT0/VAABym+x0Ii1nh7bE+WChkg3C2gWW/q+50+Xdjc4G8+UnbbX2BuDjC8PpCpyIwzvNF5TMUTFAvlbYzMgh9uBt+skeIBZasQ62DoQqKJjfx2Nz303zAUcvOv1JQBo4XRKATyiLMIonkaeNjeVrs4XoS2GxK15F6X0xhM94MtVwVKMf37nDvxQwLUhiih0hMuaBjyzYle8yAEdjRuoTeaMHXzlqTNKVuGozCS79FcNIq333PsekReqF0kguYzlGmC1Vnxh5i8b8+i49j7P3jw9v29FNubKnEn40mlidfGnbWhhiDokOnWyDJBdBnrdcCkRX81ZdIO2yjFJ8lWF1cKmBwpUM0g1wZBwNGzJbjcsu2zgmKpBapqRAWyglKuFm4pyhF1H32QID/kl9xgyP1b3vhWMw2vXnG5wL2iIJP7vgZkX+9nzO+OtRqyPijhljnZVUo5Yq9L2CvKtUgRoQ12P/V3hH7lS4vZUruXU5kfw6MLIo3KxAwebblvoQKf02Nl0B5v9ZCAvCVieozLsJIKzv/GVXThb2MVvUloarmyW8dLyJgUFaCw9NAD28FeXd5V/hP+x77mvY6Y2yKWu3k42dZ8FUSSoVV7WwUJZfwHcJQtqn+7uBBM+aoeYDJMYvokik+sGHKoJF2DBq7XRCVylLitIZ+YhIL54CxI=
  on:
    tags: true
    branch: master
    repo: jakobmattsson/rename-arguments
